version: '3.8'

services:
  db:
      image: postgres:latest
      container_name: db_postgres
      volumes:
        - /educational_platform_db/postgres:/var/lib/postgres/data
      expose:
        - 5432
      ports:
        - "5432:5432"
      env_file:
        - .env
  web:
      container_name: backend
      build:
         dockerfile: Dockerfile
         context: ././
      volumes:
        - .:/educational_platform
      expose:
        - 8000
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db
