# Generated by Django 4.2.6 on 2023-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
                "ordering": ["name", "date_created"],
            },
        ),
    ]
