# Generated by Django 4.2.6 on 2023-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0003_create_model_Article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
            options={
                "verbose_name": "Изоброжение",
                "verbose_name_plural": "Изоброжения",
                "ordering": ["image", "date_created"],
            },
        ),
    ]
