# Generated by Django 4.2.6 on 2023-11-23 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0005_create_model_Topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["name", "content", "date_created"],
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
            },
        ),
    ]
